Feature: Install official plugin
ditrit/leto-modelizer-plugin-cli pull request #19
Opened 2023-04-26 09:12 UTC by justinehell

Add prompt to choose between official or custom plugins via `install` command.
Resolve https://github.com/ditrit/leto-modelizer-plugin-cli/issues/8

2023-04-26 09:39 UTC, k-y0u requested changes

2023-04-26 09:39 UTC, k-y0u commented on src/commands/Install.js
> +      console.log(`\n${chalk.blue.bold('⚒')} Installing plugin(s) via npm...`);
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +    return [];
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +  console.log(`\n${chalk.blue.bold('⚒')} Official plugin(s) : ${pluginNames.join(', ')}.\n`);
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +    return [];
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +  args.forEach((arg) => {
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +  return parsedArgs;
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +  return selectedPlugins;
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +  return customPlugin;
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +    return customPlugin;
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +  return customPlugin;
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +  const customPromptPlugin = await getCustomPlugin();
jump line before

2023-04-26 09:39 UTC, k-y0u commented on src/services/helper.js
> +    return [];
jump line before

2023-05-02 12:02 UTC, Zorin95670 commented on src/services/helper.js
> +    return [];
No more relevant, related to old code version.

2023-05-02 12:02 UTC, Zorin95670 commented on src/services/helper.js
> +  console.log(`\n${chalk.blue.bold('⚒')} Official plugin(s) : ${pluginNames.join(', ')}.\n`);
No more relevant, related to old code version.

2023-05-02 12:02 UTC, Zorin95670 commented on src/services/helper.js
> +    return [];
No more relevant, related to old code version.

2023-05-02 12:02 UTC, Zorin95670 commented on src/services/helper.js
> +  args.forEach((arg) => {
No more relevant, related to old code version.

2023-05-02 12:03 UTC, Zorin95670 commented on src/services/helper.js
> +  return customPlugin;
No more relevant, related to old code version.

2023-05-02 12:03 UTC, Zorin95670 commented on src/services/helper.js
> +  return selectedPlugins;
No more relevant, related to old code version.

2023-05-02 12:03 UTC, Zorin95670 commented on src/services/helper.js
> +  const customPromptPlugin = await getCustomPlugin();
No more relevant, related to old code version.

2023-05-02 12:03 UTC, Zorin95670 commented on src/services/helper.js
> +    return [];
No more relevant, related to old code version.

2023-05-02 12:15 UTC, Zorin95670 commented on README.md
> +### List of official plugins
How to define official plugins

2023-05-02 12:16 UTC, Zorin95670 commented on README.md
> +### List of official plugins
Indicate before that we must define an official plugins list if we want to use this CLI

2023-05-02 12:16 UTC, Zorin95670 commented on README.md
> +A list of official plugins to install can be defined. For that, create a `cli.config.json` file at the root of Leto Modelizer project. Each object represent a plugin. Example :
Reword your sentence to be more like an "how to"

2023-05-02 12:17 UTC, Zorin95670 commented on changelog.md
> +- Add prompt to choose between official or custom plugins via `install` command.
Add:
```
- Externalize official plugins list in leto-modelizer
```

2023-05-02 12:19 UTC, justinehell commented on changelog.md
> +- Add prompt to choose between official or custom plugins via `install` command.
done

2023-05-02 13:09 UTC, Zorin95670 commented on src/services/PluginValidator.js
> +    return pluginNameRegex.test(this.name) && repositoryUrlRegex.test(this.url);
```
return this.isPluginNameValid() && this.isRepositoryUrlValid();
```

2023-05-02 13:17 UTC, justinehell commented on README.md
> +### List of official plugins
first done, second -> add log to indicate `no official plugins available` if official plugins list is empty or doesn't exist

2023-05-02 13:18 UTC, Zorin95670 commented on src/services/PromptPluginRetriever.js
> +  if (!fs.existsSync('leto-modelizer-plugin-cli.json')) {
change by:
```js
function getPluginsFromConfig() {
  if (!fs.existsSync('leto-modelizer-plugin-cli.json')) {
    return [];
  }
  
  return JSON.parse(fs.readFileSync('leto-modelizer-plugin-cli.json', 'utf8'));
}

async function getOfficialPlugins() {
  const plugins = getPluginsFromConfig();

  if (plugins.length === 0) {
    console.log(`\n${chalk.red('✘')} No official plugins available.`);

    return [];
  }
(...)  
```

2023-05-02 13:29 UTC, justinehell commented on src/services/PromptPluginRetriever.js
> +  if (!fs.existsSync('leto-modelizer-plugin-cli.json')) {
done

2023-05-02 13:36 UTC, merged